### ISSUE TITLE
More/custom sorting options

### ISSUE THREAD

**Issue by mfinell** [Aventyret/solarplexus#22]
There is currently a setting to change in which order posts should be displayed, ascending or descending by date. We should add support for sorting by title and menu_order by default.

We should also enable custom sorting options by post meta. This could be defined in the config:

```php
$config[] = [
  ...
  'order_by' => [
    'post_title', 
    '_event_date', 
    ...
  ]
] 
```

**Comment by perarnborg** [comment]
This was solved in #58
