### ISSUE TITLE
noOfPosts array for handpicked posts

### ISSUE THREAD

**Issue by tyte** [Aventyret/solarplexus#79]
Hi! I would like to know if there is a way to create an array option for `noOfPosts` when using handpicked posts? This option is available for dynamic posts.

**Comment by perarnborg** [comment]
@tyte I believe this was added to hand picked blocks in v1.10.0. I can see now that the documentation does not show this yet, we will make sure to fix that!

However, if you upgrade to the latest version (v1.10.2) I think you should be good to go! 

Let us know if I have misunderstood you!

**Comment by perarnborg** [comment]
(the docs are updated now)

**Comment by tyte** [comment]
Sounds great, thank you!
